spring.application.name=vv_backend

# Configuration de la base de données à partir des variables d'environnement Docker
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.url=/openapi/openapi.yaml

# Ressources statiques
spring.resources.static-locations=classpath:/openapi/
spring.web.resources.static-locations=classpath:/openapi/